AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Cognito User Pool & Clients for Authentication

Resources:
  emailConfigSet:
    Type: AWS::SES::ConfigurationSet
    Properties:
      Name: intllpnt-iapps-dev-ses-template

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: intllpnt-iapps-dev-userpool
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
          TemporaryPasswordValidityDays: 7
      UsernameConfiguration:
        CaseSensitive: true
      AliasAttributes:
        - email
        - preferred_username
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT
      MfaConfiguration: "OFF"
      Schema:
          - AttributeDataType: String
            Mutable: true
            Name: email
            Required: true
          - AttributeDataType: String
            Mutable: true
            Name: preferred_username
            Required: false
          - AttributeDataType: String
            Mutable: true
            Name: given_name
            Required: true
          - AttributeDataType: String
            Mutable: true
            Name: family_name
            Required: true
          - AttributeDataType: String
            Mutable: true
            Name: name
            Required: true
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: intllpnt-iapps-dev-jobs
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      GenerateSecret: true
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
      EnableTokenRevocation: true
      PreventUserExistenceErrors: ENABLED
      AccessTokenValidity: 1
      IdTokenValidity: 1
      RefreshTokenValidity: 30
      SupportedIdentityProviders:
        - COGNITO
      CallbackURLs:
        - http://localhost

Outputs:
  UserPoolInfo:
    Description: The User Pool Configured.
    Value: !Ref UserPool
    Export:
      Name: !Sub "${AWS::StackName}-userpool"
  UserPoolClientInfo:
    Description: The User Pool Client Configuration
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub "${AWS::StackName}-userpool-client"
  EmailConfigSetInfo:
    Description: The SES Email ConfigSet
    Value: !Ref emailConfigSet
    Export:
      Name: !Sub "${AWS::StackName}-ses-config-set"